version: '3.8'

services:
  web:
    build: .
    image: image_lines
    container_name: web_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lines
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  db:
    image: postgres:14-alpine
    container_name: db_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lines
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

