DROP TABLE IF EXISTS lines CASCADE;
DROP TABLE IF EXISTS sequences CASCADE;

CREATE TABLE IF NOT EXISTS lines(
id BIGSERIAL PRIMARY KEY,
line VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS sequences (
id BIGSERIAL PRIMARY KEY,
line_id BIGINT NOT NULL,
data VARCHAR NOT NULL,
CONSTRAINT fk_line_id FOREIGN KEY(line_id) REFERENCES lines(id)
);
